"""Drum pattern loader for LLM-generated MIDI events.

Patterns are generated by the LLM (Claude Code) during conversation
and saved as JSON files. This module loads and validates them.
"""

import json
import os

# GM Drum Map
GM_KICK = 36
GM_SNARE = 38
GM_CLAP = 39
GM_HAT_CLOSED = 42
GM_HAT_OPEN = 46
GM_CRASH = 49
GM_RIDE = 51
GM_RIM = 37
GM_COWBELL = 56

VALID_NOTES = {GM_KICK, GM_SNARE, GM_CLAP, GM_HAT_CLOSED, GM_HAT_OPEN,
               GM_CRASH, GM_RIDE, GM_RIM, GM_COWBELL}


def _validate_patterns(data, nbars):
    """Validate and clean pattern data. Returns (patterns, bar_sequence)."""
    if not isinstance(data, dict):
        raise ValueError('Data is not a dict')

    patterns = data.get('patterns')
    bar_sequence = data.get('bar_sequence')

    if not isinstance(patterns, dict) or len(patterns) == 0:
        raise ValueError('Missing or empty patterns')
    if not isinstance(bar_sequence, list):
        raise ValueError('Missing bar_sequence')

    # Ensure silent pattern exists
    if 'silent' not in patterns:
        patterns['silent'] = []

    # Pad or trim bar_sequence to exact length
    if len(bar_sequence) < nbars:
        last = bar_sequence[-1] if bar_sequence else list(patterns.keys())[0]
        bar_sequence.extend([last] * (nbars - len(bar_sequence)))
    bar_sequence = bar_sequence[:nbars]

    # Resolve unknown pattern references
    valid_ids = set(patterns.keys())
    first_id = list(patterns.keys())[0]
    for i, pid in enumerate(bar_sequence):
        if pid not in valid_ids:
            bar_sequence[i] = first_id

    # Validate each pattern's events
    for pat_id in list(patterns.keys()):
        events = patterns[pat_id]
        if not isinstance(events, list):
            patterns[pat_id] = []
            continue
        clean = []
        for ev in events:
            if not isinstance(ev, (list, tuple)) or len(ev) < 3:
                continue
            try:
                beat = float(ev[0])
                note = int(ev[1])
                vel = int(ev[2])
            except (ValueError, TypeError):
                continue
            beat = max(0.0, min(3.875, beat))
            vel = max(1, min(127, vel))
            if note in VALID_NOTES:
                clean.append([beat, note, vel])
        patterns[pat_id] = clean

    return patterns, bar_sequence


def _fallback_patterns(genre, nbars, arrangement):
    """Build patterns from old hardcoded genre defaults. Zero-crash fallback."""
    DEFAULTS = {
        'trap': {
            'kick': [0, 2], 'snare': [2], 'hat': '16th',
            'ghost_kick': 3.5,
        },
        'boombap': {
            'kick': [0], 'snare': [1, 3], 'hat': '8th',
            'ghost_kick': None,
        },
        'jazzhouse': {
            'kick': [0, 1, 2, 3], 'snare': [1, 3], 'hat': '16th',
            'ghost_kick': None,
        },
        'progressive_house': {
            'kick': [0, 1, 2, 3], 'snare': [1, 3], 'hat': '16th',
            'ghost_kick': None,
        },
        'rnb': {
            'kick': [0], 'snare': [1, 3], 'hat': '8th',
            'ghost_kick': 2.5,
        },
        'drill': {
            'kick': [0], 'snare': [1, 3], 'hat': '16th',
            'ghost_kick': 3.5,
        },
        'melodic_trap': {
            'kick': [0, 2], 'snare': [1, 3], 'hat': '8th',
            'ghost_kick': 3.5,
        },
        '2hollis': {
            'kick': [0, 1, 2, 3], 'snare': [1, 3], 'hat': '16th',
            'ghost_kick': None,
        },
        'techno': {
            'kick': [0, 1, 2, 3], 'snare': [1, 3], 'hat': '16th',
            'ghost_kick': None,
        },
    }

    d = DEFAULTS.get(genre, DEFAULTS['trap'])

    # Build hat events
    hat_events = []
    if d['hat'] == '8th':
        for i in range(8):
            vel = 55 if i % 2 == 0 else 35
            hat_events.append([i * 0.5, GM_HAT_CLOSED, vel])
    elif d['hat'] == '16th':
        for i in range(16):
            if i % 4 == 0:
                vel = 55
            elif i % 2 == 0:
                vel = 40
            else:
                vel = 28
            hat_events.append([i * 0.25, GM_HAT_CLOSED, vel])

    pat_a = []
    for k in d['kick']:
        pat_a.append([float(k), GM_KICK, 100])
    for s in d['snare']:
        pat_a.append([float(s), GM_CLAP, 90])
    pat_a.extend(hat_events)

    pat_b = list(pat_a)
    if d['ghost_kick'] is not None:
        pat_b = pat_a + [[float(d['ghost_kick']), GM_KICK, 55]]

    patterns = {'A': pat_a, 'B': pat_b, 'silent': []}

    bar_sequence = []
    for bar in range(nbars):
        in_section = False
        for name, s, e, kick_on, fx in arrangement:
            if s <= bar < e:
                if not kick_on:
                    bar_sequence.append('silent')
                else:
                    bar_sequence.append('A' if bar % 4 < 3 else 'B')
                in_section = True
                break
        if not in_section:
            bar_sequence.append('silent')

    return patterns, bar_sequence


def load_drum_patterns(json_path, nbars):
    """Load drum patterns from a JSON file. Returns (patterns, bar_sequence)."""
    with open(json_path, 'r') as f:
        data = json.load(f)
    patterns, bar_sequence = _validate_patterns(data, nbars)
    n_pats = len([k for k in patterns if k != 'silent'])
    total_events = sum(len(v) for v in patterns.values())
    print(f'  [drum_gen] Loaded {n_pats} patterns ({total_events} events) from {os.path.basename(json_path)}')
    return patterns, bar_sequence


def get_drum_patterns(genre, nbars, arrangement, drums_json=None):
    """Get drum patterns from JSON file or fallback.

    Args:
        genre: genre string
        nbars: total bars in song
        arrangement: arrangement list from genre config
        drums_json: path to JSON file with patterns (generated by Claude Code)

    Returns: (patterns_dict, bar_sequence_list)
    """
    if genre == 'breakcore':
        return None

    if drums_json and os.path.exists(drums_json):
        try:
            return load_drum_patterns(drums_json, nbars)
        except Exception as e:
            print(f'  [drum_gen] Failed to load {drums_json} ({e}) — using fallback')
            return _fallback_patterns(genre, nbars, arrangement)
    else:
        if drums_json:
            print(f'  [drum_gen] File not found: {drums_json} — using fallback')
        else:
            print(f'  [drum_gen] No drum pattern file — using fallback')
        return _fallback_patterns(genre, nbars, arrangement)
